name: Publish release build to repo.broccol.ai

on:
    release:
        types: [ created ]
    workflow_dispatch:

permissions:
    contents: read

jobs:
    publish:
        runs-on: ubuntu-latest

        steps:
            -   name: Check out sources
                uses: actions/checkout@v6

            -   name: Set up Java
                uses: actions/setup-java@v5
                with:
                    distribution: 'temurin'
                    java-version: '25'

            -   name: Set up Gradle
                uses: gradle/actions/setup-gradle@v6

            -   name: Publish package
                run: ./gradlew build publish -x requireClean -x signMavenPublication
                env:
                    ORG_GRADLE_PROJECT_broccolaiUsername: ${{ secrets.BROCCOLAI_USERNAME }}
                    ORG_GRADLE_PROJECT_broccolaiPassword: ${{ secrets.BROCCOLAI_PASSWORD }}
